# Generated by Django 3.1.4 on 2021-08-22 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210819_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 17, 51, 50, 307832)),
        ),
    ]
