# Generated by Django 3.1 on 2021-08-30 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210822_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 14, 16, 12, 127777)),
        ),
    ]
