# Generated by Django 3.1 on 2021-08-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210830_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 19, 50, 2, 162357)),
        ),
    ]
