# Generated by Django 3.1 on 2021-12-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211212_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='asdasd', max_length=150),
            preserve_default=False,
        ),
    ]
